server:
  port: 8080
#配置数据库链接

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://192.168.1.101:3306/VaccineDB?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
      # 文件上传配置
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB

      # 静态资源访问配置
    mvc:
      static-path-pattern: /images/**
    web:
      resources:
         static-locations: classpath:/static/,file:${user.dir}/uploads/

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entiity


#  #pagehelper配置
  pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql

# 自定义配置
upload:
  path: ${user.dir}/uploads/

